### ISSUE TITLE
32 bit debug crash on open previous target

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#1]
steps:
1. run x32 debugger
2. press the button to open up previous binary
3. crash:

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/7d99fde9-d176-479e-afe5-6ab5a26bd7f5)

after Retry pressed:
![image](https://github.com/CpuDbg/CpuDbg/assets/765343/24379cef-5582-4761-90cc-d8d473931aaf)

dump file attached

[2023-07-29_14-08-07_00000000_016208B2-80000003.zip](https://github.com/CpuDbg/CpuDbg/files/12206949/2023-07-29_14-08-07_00000000_016208B2-80000003.zip)

**Comment by CpuDbg** [comment]
This issue may also be caused by MBCS. Thank you for your feedback.

**Comment by CpuDbg** [comment]
The mbcs problem has been fixed in cpudbg v0.7.5 release.
