### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#13]
Please describe steps how to write and add plugins into debugger

I see it is looking for it on start:

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/3e78ef6a-6bf7-42e0-8449-54926e8e5b77)

**Comment by CpuDbg** [comment]
The plug-in sdk will not be opened until the debugger function is complete, and the plug-in sdk has not yet been completed.
