### ISSUE TITLE
V0.8.5 UI 有问题 及 无法运行

### ISSUE THREAD

**Issue by peter8777555** [CpuDbg/CpuDbg#18]
我使用 屏幕录影
SCREEN2EXE/SCREEN2SWF
https://www.screen-record.com/screen2exe.htm

[Demo.zip](https://github.com/user-attachments/files/16746677/Demo.zip)

**Comment by CpuDbg** [comment]
这个也是DPI和UIPI问题导致的,感谢反馈,下个版本修复.
