### ISSUE TITLE
调试 16 bit 程序 没作用 ?

### ISSUE THREAD

**Issue by peter8777555** [CpuDbg/CpuDbg#19]
http://www.ollydbg.com/Windows/Windows.htm#Windows16

0x0E). 调试 16 bit 程序
0x0F). 调试 32 bit 程序
0x10). 调试 64 bit 程序

调试 16 bit 程序 没作用 ?

![z2](https://github.com/user-attachments/assets/a6df8e72-680e-4021-9452-4769fec10340)

**Comment by CpuDbg** [comment]
16位还未实现.

**Comment by CpuDbg** [comment]
16位仿真我可能会用unicorn实现.(但考虑到要填补BIOS中断环境过于麻烦)
也有可能会用bochs qemu之类的虚拟机实现.

**Comment by CpuDbg** [comment]
目前 cpudbg 仅支持 x86 32 64

**Comment by peter8777555** [comment]
目前还没见过哪个 Debugger 能全面支持,
期待 16/32/64 位程序 完整支持.

另外想问下:
16 位 除了有 DOS,
还有 Windows V1.01 到 3.1(Windows NE),
这有无可能也一并支持 ?

这样 你的 Debugger 就 非常非常 完整了.

**Comment by CpuDbg** [comment]
> 目前还没见过哪个 Debugger 能全面支持, 期待 16/32/64 位程序 完整支持.
> 
> 另外想问下: 16 位 除了有 DOS, 还有 Windows V1.01 到 3.1(Windows NE), 这有无可能也一并支持 ?
> 
> 这样 你的 Debugger 就 非常非常 完整了.

这个我没有考虑这么多...
我之所以想要兼容16位主要是为了方便分析bootkit rootkit 以及 mbr病毒之类的.
