### ISSUE TITLE
32 bit debug crash on open itself

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#2]
if you try to debug yourself, eg:
"CpuDbg x32.exe" "CpuDbg x32.exe" 

the debugger will open up but then silently crash

crash dump attached
[2023-07-29_14-14-32_00000000_006710AB-80000003.zip](https://github.com/CpuDbg/CpuDbg/files/12206957/2023-07-29_14-14-32_00000000_006710AB-80000003.zip)

**Comment by CpuDbg** [comment]
I have tested it, and I couldn't reproduce the bug. By analyzing the crash dump (dmp), it is possible that the issue is related to MBCS encoding. We will need to wait until I update it to UNICODE and then test again. Thank you for your feedback.
