### ISSUE TITLE
Debugger silently crashes on open up Scripts window

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#4]
Debugger silently crashes on trying to open up Plugin -> ODbgScript -> Scripts window

**Comment by CpuDbg** [comment]
Unfortunately, the scripting functionality is not yet completed :( 😢

**Comment by greenozon** [comment]
OK, thanks for prompt reply!

Then I suggest to remove this plugin until it becomes GA?...

**Comment by CpuDbg** [comment]
Thank you for reporting the bug, and I have already responded to you on GitHub. Please continue to provide feedback on GitHub if you have any further questions or issues. Thank you for your support!
http://www.Ollydbg.com/  <http://www.Ollydbg.com/ >
Cpudbg x96全栈调试器 <http://www.Ollydbg.com/ >
穿山甲信息技术有限公司 <http://www.Ollydbg.com/ >
------------------------------------------------------------------
发件人：Alex ***@***.***>
发送时间：2023年7月29日(星期六) 19:23
收件人：CpuDbg/CpuDbg ***@***.***>
抄　送：Subscribed ***@***.***>
主　题：[CpuDbg/CpuDbg] Debugger silently crashes on open up Scripts window (Issue #4)
Debugger silently crashes on trying to open up Plugin -> ODbgScript -> Scripts window

**Comment by greenozon** [comment]
I guess we need to have a new build, mainly about fix for issues with MBCS

**Comment by CpuDbg** [comment]
> OK, thanks for prompt reply!
> 
> Then I suggest to remove this plugin until it becomes GA?...

I will remove all unfinished plugins in the next version, and add them back only when all functionalities are completed. Thank you for your feedback.

**Comment by CpuDbg** [comment]
> I guess we need to have a new build, mainly about fix for issues with MBCS

My entire project currently uses the MBCS character set, and converting it to UNICODE would be a significant undertaking. It is likely that the replacement of MBCS with UNICODE will happen in a future version, such as v0.7.5 or v0.7.6, or possibly even later versions.

**Comment by CpuDbg** [comment]
The mbcs problem has been fixed in cpudbg v0.7.5 release.😉
