### ISSUE TITLE
Missing readme

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#5]
Could you please add readme that will have a link to the location when users could get fresh updates?
for the moment it's not clear where to go and what site is genuine....
Thanks

**Comment by CpuDbg** [comment]
I'll be perfecting it this week...🍺

**Comment by CpuDbg** [comment]
download: https://github.com/CpuDbg/CpuDbg/releases/download/Debugger/CpuDbg.v0.7.6.7z
