### ISSUE TITLE
CpuDbg v0.7.6 - crash on run of CpuDbg x32.exe

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#6]
try to run - it is crashing and showing this error:
why?

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/b1d88022-b6d0-47b3-961c-8f229f4b91f6)

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/b620ac5b-374c-4d44-aaec-b6c8af7dcaf6)

**Comment by CpuDbg** [comment]
Can you send me the *.dmp file for a look?

**Comment by CpuDbg** [comment]
I just ran the test on the win2008 English system and found this problem. It will be fixed in the next version, thanks for the feedback.

**Comment by CpuDbg** [comment]
[CpuDbg x32.zip](https://github.com/CpuDbg/CpuDbg/files/12450781/CpuDbg.x32.zip)

![image](https://github.com/CpuDbg/CpuDbg/assets/134661959/52cbbefe-c055-4ac1-99c5-78a8a9b15af8)

This is fixed, you can download and try
