### ISSUE TITLE
CpuDbg x96.exe crashes on application restart

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#7]
when clicking "<<" icon

shows this window:

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/e53c3c01-a11f-45ba-b7e7-65d37e85042f)

**Comment by CpuDbg** [comment]
Does this problem occur randomly? Or is it a steady occurrence?

**Comment by greenozon** [comment]
randomly, trying to collect clear steps...

BTW, you did a fresh build for x32 ,binary, how about x64 one?
