### ISSUE TITLE
English menus - not translated

### ISSUE THREAD

**Issue by greenozon** [CpuDbg/CpuDbg#8]
Not all menus translated to English when English is selected as debugger interface language, eg:

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/3169d56c-2cb4-49d4-ae8a-2af568916757)

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/9cdd310b-bbbb-4bd2-b2ad-71782bc35851)

![image](https://github.com/CpuDbg/CpuDbg/assets/765343/a461db44-bb23-4bf6-9dbc-d9ec7f7536e3)

**Comment by CpuDbg** [comment]
Thanks for the feedback. This part of the function has not been perfected. Including themes and fonts, etc., it will be revised later.
